/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedOneTimeCodeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getExpectedCode"
      | "isInitialized"
      | "protocolId"
      | "setExpectedCode"
      | "verifyCode"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CodeVerified" | "ExpectedCodeSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getExpectedCode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setExpectedCode",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCode",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getExpectedCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setExpectedCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyCode", data: BytesLike): Result;
}

export namespace CodeVerifiedEvent {
  export type InputTuple = [user: AddressLike, resultHandle: BytesLike];
  export type OutputTuple = [user: string, resultHandle: string];
  export interface OutputObject {
    user: string;
    resultHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpectedCodeSetEvent {
  export type InputTuple = [setter: AddressLike];
  export type OutputTuple = [setter: string];
  export interface OutputObject {
    setter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedOneTimeCode extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedOneTimeCode;
  waitForDeployment(): Promise<this>;

  interface: EncryptedOneTimeCodeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getExpectedCode: TypedContractMethod<[], [string], "view">;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  setExpectedCode: TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyCode: TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getExpectedCode"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setExpectedCode"
  ): TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyCode"
  ): TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "CodeVerified"
  ): TypedContractEvent<
    CodeVerifiedEvent.InputTuple,
    CodeVerifiedEvent.OutputTuple,
    CodeVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "ExpectedCodeSet"
  ): TypedContractEvent<
    ExpectedCodeSetEvent.InputTuple,
    ExpectedCodeSetEvent.OutputTuple,
    ExpectedCodeSetEvent.OutputObject
  >;

  filters: {
    "CodeVerified(address,bytes32)": TypedContractEvent<
      CodeVerifiedEvent.InputTuple,
      CodeVerifiedEvent.OutputTuple,
      CodeVerifiedEvent.OutputObject
    >;
    CodeVerified: TypedContractEvent<
      CodeVerifiedEvent.InputTuple,
      CodeVerifiedEvent.OutputTuple,
      CodeVerifiedEvent.OutputObject
    >;

    "ExpectedCodeSet(address)": TypedContractEvent<
      ExpectedCodeSetEvent.InputTuple,
      ExpectedCodeSetEvent.OutputTuple,
      ExpectedCodeSetEvent.OutputObject
    >;
    ExpectedCodeSet: TypedContractEvent<
      ExpectedCodeSetEvent.InputTuple,
      ExpectedCodeSetEvent.OutputTuple,
      ExpectedCodeSetEvent.OutputObject
    >;
  };
}
